# Copyright 2018 Bitwise IO
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# -----------------------------------------------------------------------------

version: '2.1'

services:

  bond-cli:
    image: bond-cli
    container_name: bond-cli
    build:
      context: .
      dockerfile: ./cli/Dockerfile
    volumes:
      - '.:/project/sawtooth-bond'
    command: |
      bash -c "
        cd cli
        cargo build
        bond-cli init --url bond-rest-api:8000
        tail -f /dev/null
      "

  bond-processor:
    image: bond-processor
    container_name: bond-processor
    build:
      context: .
      dockerfile: ./processor/Dockerfile
    volumes:
      - '.:/project/sawtooth-bond'
    command: |
      bash -c "
        cd processor
        cargo build &&
        bond-processor -v -C tcp://validator:4004
      "

  bond-rest-api:
    image: bond-rest-api
    container_name: bond-rest-api
    build:
      context: .
      dockerfile: ./rest_api/Dockerfile
    volumes:
      - '.:/project/sawtooth-bond'
    ports:
      - '8000:8000'
    environment:
      ROCKET_ADDRESS: "0.0.0.0"
      ROCKET_PORT: "8000"
    command: |
      bash -c "
        cd rest_api
        cargo build
        bond-rest-api
      "

  postgres:
    image: postgres:alpine
    container_name: bond-postgres
    restart: always
    environment:
      POSTGRES_USER: sawtooth
      POSTGRES_PASSWORD: sawtooth
      POSTGRES_DB: sawtooth-bond
    volumes:
      - './database/tables:/docker-entrypoint-initdb.d'
    ports:
      - '5432:5432'

  validator:
    image: hyperledger/sawtooth-validator:1.0
    container_name: sawtooth-validator
    expose:
      - 4004
    ports:
      - '4004:4004'
    entrypoint: |
      bash -c "
        if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
          sawadm keygen &&
          sawtooth keygen my_key &&
          sawset genesis -k /root/.sawtooth/keys/my_key.priv &&
          sawadm genesis config-genesis.batch
        fi;
        sawtooth-validator -v \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800
      "

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.0
    container_name: sawtooth-settings-tp
    depends_on:
      - validator
    entrypoint: settings-tp -v -C tcp://validator:4004

  adminer:
      image: adminer
      container_name: bond-adminer
      restart: always
      ports:
        - '8081:8080'
